### PR TITLE
Fix static output_path, should be public/docs

### PR DESCRIPTION
**Pull request by ajcastro**

### CODE REVIEW

**Comment by shalvah** [comment]
No, this is intentional. It needs to be in docs/ for GitHub Pages to work.

**Comment by ajcastro** [comment]
@shalvah I see... but maybe we need to mention it in the documentation that they need to edit it to `public/docs` for local development. Because I was surprised earlier that when I access `http://thesideprojectapi.test/docs/` it is 404-NotFound. 
Or what about if we put it in env variable like `env('SCRIBE_STATIC_OUTPUT_PATH', 'docs'),`. 
But in my opinion, it is most cases to use for local development so the sensible default value should `public/docs`.

**Comment by shalvah** [comment]
public/docs/ is the default; I switched it to docs/ for this repo so that the demo works via GitHub Pages.

On your local machine, you can just open the docs/index.html file in your browser—no need to go through the Laravel app. Otherwise, feel free to switch it back to public/docs/ locally.

**Comment by shalvah** [comment]
Oh, if you mean the README of this project, I've just updated it to point out where the docs will be.

**Comment by ajcastro** [comment]
I see. Thanks for the clarification

**Pull request closed without merging**
